name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pwd
        run: pwd
      - name: doc
        uses: CaoJiayuan/action-apidoc@v0.3-alpha
        with:
          input: api
          output: docs
      - name: list
        run: ls -l
          
        
